"""Add admin reply to reviews

Revision ID: 2855c082cf86
Revises: f0821d97b1af
Create Date: 2025-10-18 23:19:01.842875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2855c082cf86'
down_revision = 'f0821d97b1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_reply', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('admin_reply')

    # ### end Alembic commands ###
