"""Add stars column with default value 5

Revision ID: f0821d97b1af
Revises: 9270d745a3c0
Create Date: 2025-10-18 22:40:00.776830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0821d97b1af'
down_revision = '9270d745a3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=False, server_default='5'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###
